[[recipe_modify]]
id = "AnemoneAcid_to_FirstAidKit"
name = "First Aid \n(from Harvestmoon)"
description = "Refined aerogels from local Harvestmoon. Cellular contaminants removed. Active compounds stabilized. Yields one refined First Aid Kit per gel unit."
category = "ProcessorAlternateRecipes"
ordering_index = 30
crafting_time = 30.0

[[recipe_modify.ingredients]]
HalfmoonVariant01 = 1

[[recipe_modify.outputs]]
FirstAidKit_Basic = 1
