[[recipe_modify]]
id = "Greeble_RoofCylinder"
name = "RoofCylinder"
description = "RoofCylinderDescription"
category = "BuilderExteriorGreebleCategory"
ordering_index = 2
DuplicatesBuilderActionData = true

[[recipe_modify.ingredients]]
Titanium = 1

[[recipe_modify.outputs]]
Greeble_RoofCylinder = 1
