[[recipe_modify]]
id = "Greeble_RoofFan_Single"
name = "RoofPump"
description = "RoofPumpDescription"
category = "BuilderExteriorGreebleCategory"
DuplicatesBuilderActionData = true

[[recipe_modify.ingredients]]
Titanium = 1

[[recipe_modify.outputs]]
Greeble_RoofFan_Single = 1
