[[recipe_modify]]
id = "RepairTool"
name = "Repair Tool"
description = "Titanium Ingot chassis with Sulfur-based welding compound and a wired battery system. Portable repair and fabrication unit. Effective on vehicles, bases, and most alloys."
category = "PersonalTool"
ordering_index = 60
crafting_time = 3.0

[[recipe_modify.ingredients]]
Titanium = 2
Rubber = 1
BasicBattery = 1
CopperWire = 1
Sulfur = 2

[[recipe_modify.outputs]]
RepairTool = 1
