[[item_type_modify]]
id = "CherimoyaChutney"
name = "Cherimoya Salad"
description = "Sliced Cherimoya fruit and Water Slug chunks over a bed of Fibrous Pulp, tossed with Sugar of Saturn. A hearty and refreshing salad, but somewhat slimy."
type_tag = "ItemType.Fuel"
use_from_inventory = true
gameplay_tags = ["ItemType.TunableData.BioFuelConsumption.Medium"]
replace_gameplay_tags = true
[item_type_modify.tunable_data]
"ItemType.TunableData.Food" = 40.0
"ItemType.TunableData.Water" = 20.0
replace_tunable_data = true
