[[item_type_modify]]
id = "OilySalad"
name = "Oily Salad"
description = "Compressed plant-like fiber in its own extracted hydrocarbon oil. Liminal flavor profile. Bowel effects unknown."
type_tag = "ItemType.Flora"
use_from_inventory = true
pickup_cue_tag = "GameplayCue.Pickup.Plant"
drop_cue_tag = "GameplayCue.Drop.Plant"
adaptations = ["Stomach.RequiredToConsume"]
gameplay_tags = ["ItemType.TunableData.BioFuelConsumption.Short"]
replace_gameplay_tags = true
[item_type_modify.tunable_data]
"ItemType.TunableData.Food" = 60.0
"ItemType.TunableData.Water" = 20.0
replace_tunable_data = true
