[[item_type]]
id = "BiogenicPFCEmulsion"
name = "Biogenic PFC Emulsion"
description = "A liquid-breathing emulsion made from local bio-proteins that damages tissue, but provides a critical burst of emergency oxygen. Inhale through nose for maximum effect."
template = "IsotonicDrink"
icon = "FILE MOD Icons/T_Alcohol_Icon.png"
type_tag = "ItemType.Flora"
equipment_slot = "Character.Slot.Tool"
use_from_inventory = true
pickup_cue_tag = "GameplayCue.Pickup.Liquid"
drop_cue_tag = "GameplayCue.Drop.Liquid"
gameplay_tags = ["ItemType.TunableData.BioFuelConsumption.Short"]
[item_type.tunable_data]
"ItemType.TunableData.Food" = -15.0
"ItemType.TunableData.Health" = -30.0
"ItemType.TunableData.Oxygen" = 30.0
"ItemType.TunableData.Water" = -15.0
