[[recipe_modify]]
id = "Axum_Jar"
name = "AxumJar"
description = "AxumJarDescription"
category = "BuilderFurniture_Axum_Category"
ordering_index = 1
DuplicatesBuilderActionData = true

[[recipe_modify.ingredients]]
Copper = 1

[[recipe_modify.outputs]]
Axum_Jar = 1
