[[recipe_modify]]
id = "SilverToSIlverIngot"
name = "Silver Ingot"
description = "Silver ore cast into a solid machining Ingot. Soft, highly conductive, and seawater-resistant. Primary conductor material for mid-tier electronics fabrication."
category = "Processor_Ingots"
ordering_index = 31
crafting_time = 60.0

[[recipe_modify.ingredients]]
Silver = 4

[[recipe_modify.outputs]]
SilverIngot = 1
