[[recipe_modify]]
id = "ComputerChip"
name = "System Chip"
description = "Quartz-substrate microchip wired to a Silver-Copper harness using Coral shavings and etched in acid. Compact, energy-efficient, mobile. The most computation you can hold with one hand."
category = "ResourcesElectronics"
ordering_index = 50

[[recipe_modify.ingredients]]
PlateCoral = 2
Quartz = 2
WiringKit = 1
MildAcid = 1

[[recipe_modify.outputs]]
ComputerChip = 1
