[[recipe_modify]]
id = "MetalSalvage"
ordering_index = 10
name = "Salvaged Titanium"
description = "Crudely convert salvage into raw titanium."
category = "ResourcesRawMaterials"
crafting_time = 2.0

[[recipe_modify.ingredients]]
MetalSalvage = 1

[[recipe_modify.outputs]]
Titanium = 6
