[[recipe_modify]]
id = "CeilingLight_Rect_A"
name = "RectangularCeilingLight"
description = "RectangularCeilingLightDescription"
category = "BuilderBaseObject_Lighting"
ordering_index = 1
DuplicatesBuilderActionData = true

[[recipe_modify.ingredients]]
Titanium = 2
Quartz = 2

[[recipe_modify.outputs]]
CeilingLight_Rect_A = 1
