[[recipe_modify]]
id = "Light_Wall_Small"
name = "WallLightSmall"
description = "WallLightSmallDescription"
category = "BuilderBaseObject_Lighting"
ordering_index = 2
DuplicatesBuilderActionData = true

[[recipe_modify.ingredients]]
Titanium = 1
Quartz = 1

[[recipe_modify.outputs]]
Light_Wall_Small = 1
