[[item_type_modify]]
id = "HalfmoonJerky"
name = "Halfmoon Jerky"
description = "Dried Halfmoon and Geordie strips, salted and pressed in liquid-filled Fibrous Matter. Chewy and flavorful."
type_tag = "ItemType.Fuel"
use_from_inventory = true
gameplay_tags = ["ItemType.TunableData.BioFuelConsumption.Medium"]
replace_gameplay_tags = true
[item_type_modify.tunable_data]
"ItemType.TunableData.Food" = 60.0
"ItemType.TunableData.Water" = 20.0
replace_tunable_data = true
