# Basebuilding_Posters scan overrides for RealisticScans.
# scan_duration = seconds to complete one instance scan.
# num_required = unique instances needed for blueprint unlock.

[[scan_modify]]
id = "Poster_KeepSwimming"
asset = "/Game/Data/ScanData/Basebuilding/Posters/DA_Poster_KeepSwimming_ScanData.DA_Poster_KeepSwimming_ScanData"
scan_duration = 1.8
num_required = 1

[[scan_modify]]
id = "Poster_PaintedTree"
asset = "/Game/Data/ScanData/Basebuilding/Posters/DA_Poster_PaintedTree_ScanData.DA_Poster_PaintedTree_ScanData"
scan_duration = 1.8
num_required = 1

[[scan_modify]]
id = "Poster_Reprinting"
asset = "/Game/Data/ScanData/Basebuilding/Posters/DA_Poster_Reprinting_ScanData.DA_Poster_Reprinting_ScanData"
scan_duration = 1.8
num_required = 1

[[scan_modify]]
id = "Poster_ScoutRay"
asset = "/Game/Data/ScanData/Basebuilding/Posters/DA_Poster_ScoutRay_ScanData.DA_Poster_ScoutRay_ScanData"
scan_duration = 1.8
num_required = 1

[[scan_modify]]
id = "Poster_Zezura_01"
asset = "/Game/Data/ScanData/Basebuilding/Posters/DA_Poster_Zezura_01_ScanData.DA_Poster_Zezura_01_ScanData"
scan_duration = 1.8
num_required = 1

[[scan_modify]]
id = "Poster_Zezura_02"
asset = "/Game/Data/ScanData/Basebuilding/Posters/DA_Poster_Zezura_02_ScanData.DA_Poster_Zezura_02_ScanData"
scan_duration = 1.8
num_required = 1
