[[recipe_modify]]
id = "Tadpole_CrushDepthUpgrade_02"
name = "Tadpole Depth Module Mk. 2"
description = "Germanium and Plasteel fused to an Enameled Glass hull insert, processed by a Dedicated Core. This one doubles the active pressure compensation allowing for significantly deeper operation. Does not stack with itself."
category = "TadpoleUpgrades"
ordering_index = 10000

[[recipe_modify.ingredients]]
AxumAlloyIngot = 2
EnameledGlass = 4
GermaniumIngot = 4
Atacamite = 8
ComputerChipMk2 = 1
WiringKit = 1

[[recipe_modify.outputs]]
Tadpole_CrushDepthUpgrade02 = 1
