[[recipe_modify]]
id = "Tadpole_EngineEfficiency"
name = "Engine Efficiency"
description = "Strontium and Lithium regulated power modulator managed by a System Chip. Reduces engine power draw by 20% through real-time optimization. Stacks up to four times."
category = "TadpoleUpgrades"
ordering_index = 10000
DefaultRecipeState = "Locked"

[[recipe_modify.unlocking_rule]]
set_id = "DefaultRuleSet"
scan_data = ["ScanData_TadpoleMod_EngineEfficiency"]

[[recipe_modify.ingredients]]
Strontium = 2
Lithium = 2
ComputerChipMk2 = 1
WiringKit = 1

[[recipe_modify.outputs]]
Tadpole_EngineEfficiency = 1
