[[recipe_modify]]
id = "Greeble_RoofAntenna_A"
name = "RoofAntenna"
description = "RoofAntennaDescription"
category = "BuilderExteriorGreebleCategory"
ordering_index = 4
DuplicatesBuilderActionData = true

[[recipe_modify.ingredients]]
Titanium = 2

[[recipe_modify.outputs]]
Greeble_RoofAntenna_A = 1
