[[recipe_modify]]
id = "Greeble_RoofPanel_A"
name = "RoofPanelLarge"
description = "RoofPanelLargeDescription"
category = "BuilderExteriorGreebleCategory"
ordering_index = 3
DuplicatesBuilderActionData = true

[[recipe_modify.ingredients]]
Titanium = 4

[[recipe_modify.outputs]]
Greeble_RoofPanel_A = 1
