[[recipe_modify]]
id = "Poster_Preorder_01"
name = "PreorderPoster01"
category = "BuilderPostersCategory"
ordering_index = 99
DuplicatesBuilderActionData = true

[[recipe_modify.ingredients]]
Titanium = 1
Lead = 1

[[recipe_modify.outputs]]
Poster_Preorder_01 = 1
