[[recipe_modify]]
id = "PosterCommunity02"
name = "PosterCommunity02"
description = "PosterDescription"
category = "BuilderPostersCategory"
ordering_index = 12
DuplicatesBuilderActionData = true

[[recipe_modify.ingredients]]
Titanium = 1
Lead = 1

[[recipe_modify.outputs]]
Poster_Community02 = 1
