[[recipe_modify]]
id = "PosterWanted"
name = "PosterWanted"
description = "PosterWantedDescription"
category = "BuilderPostersCategory"
DuplicatesBuilderActionData = true

[[recipe_modify.ingredients]]
Titanium = 1
Lead = 1

[[recipe_modify.outputs]]
Poster_Wanted = 1
