[[recipe_modify]]
id = "Trashcan"
name = "Trashcan"
description = "TrashcanDescription"
category = "BuilderFurnitureCategory"
ordering_index = 7
DuplicatesBuilderActionData = true

[[recipe_modify.ingredients]]
Titanium = 2

[[recipe_modify.outputs]]
Trashcan = 1
