[[recipe_modify]]
id = "Light_Wall_Large"
name = "WallLightLarge"
description = "WallLightLargeDescription"
category = "BuilderBaseObject_Lighting"
ordering_index = 3
DuplicatesBuilderActionData = true

[[recipe_modify.ingredients]]
Titanium = 1
Quartz = 1

[[recipe_modify.outputs]]
Light_Wall_Large = 1
