[[recipe_modify]]
id = "Tailing_Jar_Coral"
name = "TailingJarCoral"
description = "TailingJarCoralDescription"
category = "BuilderFurniture_Tailing_Category"
ordering_index = 4
DuplicatesBuilderActionData = true

[[recipe_modify.ingredients]]
PlateCoral = 2

[[recipe_modify.outputs]]
Tailing_Jar_Coral = 1
