[[recipe_modify]]
id = "PosterPaintedTree"
name = "PaintedTreePoster"
description = "PosterGenericDescription"
category = "BuilderPostersCategory"
ordering_index = 10
DuplicatesBuilderActionData = true

[[recipe_modify.ingredients]]
Titanium = 1
Lead = 1

[[recipe_modify.outputs]]
Poster_PaintedTree = 1
