[[recipe_modify]]
id = "Pavlova"
name = "Pavlova"
description = "Deepwing Egg Yolk, Cherimoya fruit, and raw Medical Gel - sweetened with Sugar of Saturn. Structurally a dessert, yet somehow quite filling."
category = "SustenanceSalads"
ordering_index = 1000
crafting_time = 5.0

[[recipe_modify.ingredients]]
DeepwingBrooderEgg = 1
SugarAnalog = 1
CherimoyaRotsacFruit = 1
AcidAnemone_Medigel = 1

[[recipe_modify.outputs]]
Pavlova = 1
