[[recipe_modify]]
id = "ChairDining"
name = "DiningChair"
description = "DiningChairDescription"
category = "BuilderFurnitureCategory"
DuplicatesBuilderActionData = true

[[recipe_modify.ingredients]]
Titanium = 2
Rubber = 1

[[recipe_modify.outputs]]
ChairDining = 1
