[[recipe_modify]]
id = "Crate_01"
name = "SmallCrate"
description = "SmallCrateDescription"
category = "BuilderFurnitureCategory"
ordering_index = 8
DuplicatesBuilderActionData = true

[[recipe_modify.ingredients]]
Titanium = 1

[[recipe_modify.outputs]]
Crate_01 = 1
